### ISSUE TITLE
'biovec' has no attribute 'models'

### ISSUE THREAD

**Issue by AayushGrover** [kyu999/biovec#10]
I tried running the sample code given in README. I am getting the following error -

AttributeError: module 'biovec' has no attribute 'models'

I am not sure why I am getting it. I have installed 'biovec' already using pip. Any help is appreciated.

**Comment by kyu999** [comment]
Hi, it looks readme was old and does not work anymore.
I've fixed them already, so please try again!
I've corrected program to be able to follow this README, so README itself is not changed.
The newer version is 0.2.7.
