### ISSUE TITLE
Problem with SwissProt trained model

### ISSUE THREAD

**Issue by GiancarloCroce** [kyu999/biovec#4]
Hi, 
I'm running your script with python 2.7, but I'm having some problems  when I try to import the trained model:
>> import biovec
>> pv = biovec.models.load_protvec("trained_models/swissprot_reviewed_protvec")
The script throws
"AttributeError: 'ProtVec' object has no attribute 'vocabulary'.

Am I missing something?

**Comment by kyu999** [comment]
I investigated the reason, and found out that dependency library(gensim) changed, then the trained model does not follow the format of the library anymore.
So, it is not your fault.
I re-trained the model with the new format, so please try again with up-to-date version of this repository(MR #6 ).
Also, I will add the dependency information soon.

**Comment by GiancarloCroce** [comment]
Thanks! It works now
